package com.amozeshgam.amozeshgam.handler

sealed class NavigationHandler(val route: String) {
    data object HomeScreen : NavigationHandler(route = "homeScreen")
    data object NewsScreen : NavigationHandler(route = "newsScreen")
    data object ProfileScreen : NavigationHandler(route = "profileScreen")
    data object MessageScreen : NavigationHandler(route = "profileScreen/messageScreen")
    data object AllPodcastScreen : NavigationHandler(route = "homeScreen/allPodcastScreen")
    data object AllCoursesScreen : NavigationHandler("homeScreen/allPackageScreen")
    data object MyPackageScreen : NavigationHandler("profileScreen/myPackageScreen")
    data object MyRoadMapScreen : NavigationHandler("profileScreen/myRoadMapScreen")
    data object MyActiveDeviceScreen : NavigationHandler("profileScreen/myActiveDeviceScreen")
    data object MyCartScreen : NavigationHandler("myCartScreen")
    data object MyFavorites : NavigationHandler("profileScreen/myFavoritesScreen")
    data object SupportScreen : NavigationHandler("profileScreen/supportScreen")
    data object AiChatScreen : NavigationHandler("aiChatScreen")
    data object StoryScreen : NavigationHandler("storyScreen")
    data object PodcastPlayerScreen : NavigationHandler("homeScreen/podcastPlayerScreen")
    data object SingleCourseScreen : NavigationHandler("homeScreen/singlePackageScreen")
    data object FAQScreen : NavigationHandler("profileScreen/FAQScreen")
    data object InformationScreen : NavigationHandler("homeScreen/informationScreen")
    data object NotificationScreen : NavigationHandler("homeScreen/notificationScreen")
    data object TicketScreen : NavigationHandler("profileScreen/ticketScreen")
    data object SingleNewsScreen : NavigationHandler("newsScreen/singleNewsScreen")
    data object MyOrdersScreen : NavigationHandler("profileScreen/myOrdersScreen")
    data object MyTransactionsScreen : NavigationHandler("profileScreen/myTransactionsScreen")
    data object ProfileEditorScreen : NavigationHandler("profileScreen/profileEditorScreen")
    data object FieldScreen : NavigationHandler("homeScreen/fieldScreen")
    data object JobsScreen : NavigationHandler("homeScreen/jobsScreen")
    data object PaymentScreen : NavigationHandler("myCartScreen/payment")
    data object SingleSubFieldScreen : NavigationHandler("homeScreen/subField")
    data object LoginOneScreen : NavigationHandler(route = "loginOneScreen")
    data object LoginTwoScreen : NavigationHandler(route = "loginTwoScreen")
    data object LoginThreeScreen : NavigationHandler(route = "loginThreeScreen")
    data object SplashScreen : NavigationHandler(route = "splashScreen")
    data object AIQuestionScreen : NavigationHandler(route = "homeScreen/AIQuestionScreen")
    data object JobsPurchaseScreen : NavigationHandler(route = "jobsPurchaseScreen")
    data object TourScreen : NavigationHandler(route = "tourScreen")
}